spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/sfg_prod?useSSL=false
    username: sfg_prod_user
    password: manos

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false